alter table COMPOSITION_CHILD add constraint FK_COMPOSITION_CHILD_ON_PARENT foreign key (PARENT_ID) references COMPOSITION_PARENT(ID);
create index IDX_COMPOSITION_CHILD_ON_PARENT on COMPOSITION_CHILD (PARENT_ID);
